name: base
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - fastapi
  - pylama
  - numpy
  - python-dotenv
  - black
  - boto3
  - ca-certificates
  - openssl
  - fastapi-cli
  - certifi
  - psutil
  - transformers
  - pillow
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - timm
  - pip:
      - opencv-python
